### ISSUE TITLE
Internal sidebar links should open in the same window

### ISSUE THREAD

**Issue by onedrawingperday** [onweru/compose#10]
Hello @onweru 

In the latest update I noticed that [sidebars links](https://themes.gohugo.io/theme/compose/docs/) open in new tabs. However this is not good from a UX standpoint. 

Please remove the attribute `target="_blank"` from internal links.

**Comment by onweru** [comment]
@onedrawingperday,

Thank you for raising this one. I will update it and notify you

**Comment by onweru** [comment]
@onedrawingperday,

The problem is that "https://themes.gohugo.io/theme/" wasn't being recognized as the baseURL by [this snippet of javascript code](https://github.com/onweru/compose/blob/47b40fe41e5f58d736892188debf0637633eb6d6/assets/js/index.js#L266-L276) (`parentURL is equal to whatever the baseURL is`). Hence the `target=_blank` attribute was being added.

I'm not sure if the commit I just referenced above 47b40fe41e5f58d7368 will do, but it's the only thing I can think of currently being amiss.

Could it be the issue?

**Comment by onedrawingperday** [comment]
@onweru 

I don’t think that using JS is necessary for this since in a Hugo template you can perform a check and conditionally add the `target="_blank"` attribute.

For example within the context of a Hugo menu try something like:

```
{{ if strings.HasPrefix .URL "http" }} target="_blank"{{ end }}>{{ .Name }}</a>
```

**Comment by onweru** [comment]
@onedrawingperday 

You make a good point. I used js as a _one-solution-fits-all_. This way too, links inside markdown content files are attributed correctly.

I could limit the scope of the js script to the element housing `{{ .Content }}`. But then I would need to add this beautiful Hugo conditional `{{ if strings.HasPrefix .URL "http" }}` in at least one other place.

I'm curious if this 👇 was the issue. If it's not, I will need to explore other remedies.

[<img width="616" alt="Screen Shot 2020-05-29 at 9 45 53 AM" src="https://user-images.githubusercontent.com/16350351/83229876-6c729580-a191-11ea-9229-044047ac72d1.png">](https://github.com/onweru/compose/commit/47b40fe41e5f58d736892188debf0637633eb6d6)

**Comment by onedrawingperday** [comment]
No the issue is not fixed with your latest commit @onweru 

I updated your theme on the Hugo Themes website -just now- and the links still open in a new tab.

see: https://themes.gohugo.io/theme/compose/docs/

**Comment by onedrawingperday** [comment]
@onweru 

I confirm that your recent commits have fixed this issue.

The theme was updated in https://github.com/gohugoio/hugoThemes/commit/abfc371b865ccff1bc201bde7710efdd96c10ffb and the changes will be published once the Hugo Themes deploy concludes.

Thanks.

**Comment by onweru** [comment]
@onedrawingperday 

Thanks a lot for your support
