### ISSUE TITLE
[FEATURE] Global Search Option

### ISSUE THREAD

**Issue by CorruptComputer** [onweru/compose#104]
**I have checked all the prerequisites below and I don't see this is available**

- [x] Read the README.md
- [x] Have the extended version of Hugo installed
- [x] Used the exampleSite's config.toml as a reference

**Describe the feature**
Would it be possible to get an option in `config/_default/params.toml` so that search is always global on the site? For example, if you are in a directory `https://[site]/foo/bar/` and try to search for something in a different directory `https://[site]/baz/` it will not show up in the search results, as the search box is only searching in `https://[site]/foo/bar/`.

**Desktop (please complete the following information):**
 - OS: Fedora 37
 - Browser: Firefox 110

**Comment by CorruptComputer** [comment]
For reference, if you try to search for `Food` from this page: https://your-chronicle.idle.wiki/areas/village/
You will get no results, yet this page exists here: https://your-chronicle.idle.wiki/resources/food/

I think it would allow this theme to be used in more cases if the search had an option to be global, rather than just within the current directory. This index should already exist, as I think it could just use the search index from the home page which does search everywhere.

**Comment by onweru** [comment]
Done ✅ 

[<img width="879" alt="SCR-20230228-pdu" src="https://user-images.githubusercontent.com/16350351/221896872-4d5a2fd9-5329-4acd-b6ee-a88e0f465a7a.png">](https://docs.neuralvibes.com/docs/compose/search/#1-passive-search
)

**Comment by CorruptComputer** [comment]
Thank you!
