### ISSUE TITLE
[BUG] Enter to redirect to search results doesn't work in Firefox

### ISSUE THREAD

**Issue by ltguillaume** [onweru/compose#106]
**I have checked all the prerequisites below and I'm yet experiencing a problem**

- [x] Read the README.md
- [x] Have the extended version of Hugo installed
- [x] Used the exampleSite's config.toml as a reference
- [x] If and when requested, I'll link my repo to make it easier to debug.

__⚠️ NOTE:__ If the issue isn't easy to reproduce and its author(s) decline to provide reasonable accommodation to debug, the issue will be closed.

**Describe the bug**

1. The docs state that the user should be able to press Enter in the search field to be redirected to the search page. This is useful if there are more than 8 results and to see text previews of the results. However, pressing Enter does not do anything on Firefox-based browsers. I've also tested on your example site directly.

2. Even in Chromium-based browsers, when already on the search page, a new search + Enter does not produce the text previews.

**Desktop (please complete the following information):**
 - OS: Win10
 - Browser: Firefox, LibreWolf 110

**Comment by onweru** [comment]
Apparently, 'search' event isn't supported on Firefox. https://developer.mozilla.org/en-US/docs/Web/API/HTMLInputElement/search_event. Thank you, fixing it.

**Comment by ltguillaume** [comment]
Great! Thank you! 😃
