### ISSUE TITLE
[BUG] Search with global = true still shows "Search in docs" etc.

### ISSUE THREAD

**Issue by ltguillaume** [onweru/compose#107]
**I have checked all the prerequisites below and I'm yet experiencing a problem**

- [x] Read the README.md
- [x] Have the extended version of Hugo installed
- [x] Used the exampleSite's config.toml as a reference
- [x] If and when requested, I'll link my repo to make it easier to debug.

__⚠️ NOTE:__ If the issue isn't easy to reproduce and its author(s) decline to provide reasonable accommodation to debug, the issue will be closed.

**Describe the bug**
If the option `global` is set to `true` in `config/_default/params.toml`, this fact is not reflected in the search field on the website: it still says "Search in [section]", instead of always saying "Search in/on website".

**Comment by ltguillaume** [comment]
https://github.com/onweru/compose/commit/450840b51131b926b1a24362641bf67b73c03e4b introduces new problems:

1. It seems that there is no longer a way to see which section is being searched if `global` is `false`.
2. Translations now show e.g. "Suche in <no value>".

**Comment by onweru** [comment]
@ltguillaume,

This is a breaking change indeed.

This [changed](https://github.com/onweru/compose/commit/450840b51131b926b1a24362641bf67b73c03e4b#diff-3deecac61c0ada8628992e94508e12aa6a3004ea1e3549e375561d9aa0cceb60L16)

```
[search_field_placeholder]
  other = "Search {{ .section }}"
``` 

to 

```
[search_field_placeholder]
  other = "Search"
```

**Comment by onweru** [comment]
It should work now, with or without the change.

**Comment by ltguillaume** [comment]
But it seems that you removed the indicator that the user is only searching a specific section if `global = false`, right?

If I understand that correctly, I don't think that's wise.

**Comment by onweru** [comment]
@ltguillaume, that indicator still exists when global is false. I modified how it's injected. 

Previously it was baked into the translation string, that's not necessary.

**Comment by ltguillaume** [comment]
Ok, so I need to remove it from the translations, thanks. It just said `Suche in <no value>` but perhaps the section is shown after that and it was cut off due to the size of the input box. I'll check soon.

**Comment by onweru** [comment]
>  so I need to remove it from the translations

Not necessarily. I added a fallback in the template that sets the `<no value>` part to an empty string.

**Comment by onweru** [comment]
@ltguillaume,

Have you tested the new change on your local though? Because I tested and all was good. Feels like we're now arguing over theory

About the empty string, I was referencing this line

https://github.com/onweru/compose/blob/00dd32520269413918ed8250a9951820f5972df0/layouts/partials/search.html#L5

```
(dict "section" "") }}
```

👆🏼 part ensures that the right context is parsed if you have  `other = "search in"` or `other = "search in {{ .section }}"`.
