### ISSUE TITLE
[FEATURE] - Add Latest Mermaid.js Release

### ISSUE THREAD

**Issue by rwstorer** [onweru/compose#108]
**I have checked all the prerequisites below and I don't see this is available**

- [X] Read the README.md
- [X] Have the extended version of Hugo installed
- [X] Used the exampleSite's config.toml as a reference

Latest release of Mermaid.js

Could you please add the latest release of the Mermaid.js library? I think version 10 is available. I'd like to use the "tickInterval" option and it doesn't seem available in the 8.9.2 version shipped with compose.

Thanks!

**Comment by onweru** [comment]
Thanks for the heads up @rwstorer, will do so now.
