### ISSUE TITLE
[FEATURE] Add Tina CMS config

### ISSUE THREAD

**Issue by MTRNord** [onweru/compose#117]
**I have checked all the prerequisites below and I'm yet experiencing a problem**

- [x] Read the README.md
- [x] Have the extended version of Hugo installed
- [x] Used the exampleSite's config.toml as a reference
- [x] If and when requested, I'll link my repo to make it easier to debug.

__⚠️ NOTE:__ If the issue isn't easy to reproduce and its author(s) decline to provide reasonable accommodation to debug, the issue will be closed.

**Describe the bug**

Forestry has been replaced by tina. https://tina.io/forestry/ It would be nice if the config files either could be migrated or new tina ones be added to the template :)

**Comment by onweru** [comment]
Hi @MTRNord,

Working to avail a Tina config soon. Might take some time as I work on this on my free time.
