### ISSUE TITLE
Fix layout for anchor links

### ISSUE THREAD

**Issue by mk0** [onweru/compose#13]
In order to display the page correctly, when visiting an anchor link, negative margin including a positiv padding must be added to the stylesheet for the `link_owner` class in order to skip the header of the page.

Example:
```
margin-top: -80px;
padding-top: 90px;
```
This example will add a distance delta of 10px above the heading element. This will have an impact on the distance of the heading element to the header element when visiting the page using an anchor link as well as distances between headings and other siblings.

You will be able to actually see the heading this way. Currently it is behind the header of the page.
Example link: https://themes.gohugo.io//theme/compose/docs/getting-started/shortcodes/#column

**Comment by onweru** [comment]
@mk0, thanks for contributing, I will have a look at this and #14
