### ISSUE TITLE
syntax highlight

### ISSUE THREAD

**Issue by ZhengHe-MD** [onweru/compose#2]
I don't known how to configure syntax highlighting in compose theme, could you help me?

**Comment by onweru** [comment]
@ZhengHe-MD, can I see you repo? You could also view [these lines](https://github.com/onweru/compose-userguide/blob/a2c23a26d07a25c0b6bceaff19ea2482eea7bdc8/config.toml#L19-L28https://github.com/onweru/compose-userguide/blob/a2c23a26d07a25c0b6bceaff19ea2482eea7bdc8/config.toml#L19-L28) from [the guide](https://github.com/onweru/compose-userguide)

**Comment by ZhengHe-MD** [comment]
I have tried that, with different syntax highlighting schemes, but nothing happened. The repo has been deleted and it is supposed to be hosted in our private gitlab registry. If it did work, you can just add an code block with syntax highlighting to your example site, that would be more helpful.

**Comment by onweru** [comment]
my gitlab handle is **weru**, if you may I could have a look. This page https://github.com/onweru/compose-userguide/blob/master/content/docs/getting%20started/shortcodes-example.md from the guide has code blocks.

**Comment by ZhengHe-MD** [comment]
right, but the code block doesn't show any highlighting scheme here https://compose-docs.netlify.com/docs/getting-started/shortcodes-example/ , its all plain words, no colors.

**Comment by onweru** [comment]
Aha, makes sense now. pushing a fix in a few

**Comment by onweru** [comment]
@ZhengHe-MD, let me know if it's fixed now. Thanks.

**Comment by ZhengHe-MD** [comment]
@onweru  thx, that commit magically fixes this problem. Close the issue.
