### ISSUE TITLE
Disappearing Nav Items in Mobile View - Where did they go?

### ISSUE THREAD

**Issue by rjfranssen** [onweru/compose#23]
When narrowing the [demo page](https://themes.gohugo.io//theme/compose/) or viewing it on a Mobile device, the nav items appear to collapse under a single "Menu" item, though the individual nav items (e.g. Docs, Example, GitHub) are inaccessible.

I tried toying with `nav.html` and `_nav.css`, but I'm swinging a hammer blindly.

In any case, I love the theme, asante sana

#### Narrow/Mobile (collapsed "Menu"):   

<img src="https://user-images.githubusercontent.com/6855649/100372370-22029200-2fd7-11eb-97c5-e233b9f841e2.png" width="350" height="300"/>

#### Where did the nav items go? Off-screen to the left?  

<img src="https://user-images.githubusercontent.com/6855649/100372681-9a695300-2fd7-11eb-93d4-2cb73f6f8fa8.png" width="800" height="350"/>

**Comment by onweru** [comment]
@rjfranssen, I'm aware of this ... I will find the time and ensure that the nav works on mobile.
