### ISSUE TITLE
Top level folder does not have a table of contents

### ISSUE THREAD

**Issue by moldhouse** [onweru/compose#26]
**I have checked all the prerequisites below and I'm yet experiencing a problem**

- [x] Read the README.md
- [x] Have the extended version of Hugo installed
- [x] Used the exampleSite's config.toml as a reference

A clear and concise description of what the bug is. [REPLACE]

If I add a top level directory besides the 'docs' section, it does not have a table of contents. Especially I do not want to have a nested structure where 'docs' is the top level. If I rename the top level docs directory, the table of contents disappears.

**Desktop (please complete the following information):**
 - OS: MacOS
 - Browser all

**Comment by onweru** [comment]
Yes, the top level directory is supposed to contain the home page, regular pages e.g (contact page, about, ...) ... or if someone wants to add another section, say like a blog / news. The docs are to be placed inside the docs dir. I'm not sure that I have made the docs directory configurable. Thanks for the hint
