### ISSUE TITLE
Theme color customizable in config.toml

### ISSUE THREAD

**Issue by bb1950328** [onweru/compose#31]
I want to configure the `--theme` variable in `_variables.sass`.
The problem is that the sass file isn't evaluated by hugo so it's not that easy for me with my current knowledge of hugo to do it by myself.
If somebody can point me in the right direction I can do it by myself.
I would be glad if this gets implemented soon because currently I have a second git branch just to change the color.

Thank you very much

**Comment by onweru** [comment]
@bb1950328 are you running compose theme as a hugo module?

**Comment by bb1950328** [comment]
Currently it's a git submodule.

**Comment by onweru** [comment]
> Currently it's a git submodule.

Is this submodule pointing to this repo or a fork of this repo?

**Comment by bb1950328** [comment]
It's pointing to my fork:
```
[submodule "themes/compose"]
	path = themes/compose
	url = https://github.com/bb1950328/compose.git
```
I have a branch named "customize" where I changed the `--theme` variable to blue. I develop new features on "master" and merge it into "customize" after I committed them. If I can save the color in the web repo ([BrickSimWeb](https://www.github.com/bb1950328/BrickSimWeb) in my case) I wouldn't need to do that merge every time and other users can customize the theme easier as well.

**Comment by onweru** [comment]
Try:

1.  Create a `assets/sass/_variables.sass` file [on your repo](https://github.com/bb1950328/BrickSimWeb).
2.  Copy the contents of https://github.com/bb1950328/compose/blob/master/assets/sass/_variables.sass and paste into (1) above
3. Edit the `--theme` variable after completing the copy-paste. 

That file should act as a git trackable override. Please notice that the naming and nesting of the override file should match file you wish to override from the theme.

Let me know if you have some luck

**Comment by bb1950328** [comment]
It's working! Thank you very much.
