### ISSUE TITLE
Mobile menu (sidebar) broken in Firefox Mobile (codename Fenix)

### ISSUE THREAD

**Issue by rakshazi** [onweru/compose#36]
**I have checked all the prerequisites below and I'm yet experiencing a problem**

- [x] Read the README.md
- [x] Have the extended version of Hugo installed
- [x] Used the exampleSite's config.toml as a reference

**Describe the bug**

Mobile sidebar menu is broken on Firefox mobile

**Phone:**
 - OS: Android 10
 - Browser: Firefox 85.1

**Screenshoots**
![firefox-bug-portrait](https://user-images.githubusercontent.com/3428087/106756846-5bd7c080-6638-11eb-9f20-1e2df069a53f.png)
![firefox-bug-landscape](https://user-images.githubusercontent.com/3428087/106756860-5e3a1a80-6638-11eb-91a5-a654d2e9bb63.png)

**Comment by onweru** [comment]
@rakshazi, any improvements?

**Comment by rakshazi** [comment]
I will test it tomorrow, thank you!

**Comment by rakshazi** [comment]
Sorry for delay,
It works, thank you!
