### ISSUE TITLE
config: noClasses option issue

### ISSUE THREAD

**Issue by foxisawesome** [onweru/compose#37]
**I have checked all the prerequisites below and I'm yet experiencing a problem**

- [x] Read the README.md
- [x] Have the extended version of Hugo installed
- [x] Used the exampleSite's config.toml as a reference

**Describe the bug**
While changing noClasses=true in config.toml file. the site cannot be change to light mode. It stuck at dark mode. 

**Desktop (please complete the following information):**
- chrome 88

**Comment by onweru** [comment]
Umh, is [this the line](https://github.com/onweru/compose/blob/19c5ace7ad501e2b157150e17de4c55e45b35276/exampleSite/config.toml#L55) you're trying to edit?

**Comment by foxisawesome** [comment]
Actually, I am trying to change line 39: noClasses = true in the file: exampleSite\config.toml. everything else untouched. Then I compiled the site. Went to chrome, found the the dark mode switch would NOT work for pages having python code highlighting blocks. Pages not having hightlight blocks can switch between dark mode and light mode.

**Comment by onweru** [comment]
Oh, I see ... changing that will indeed break the theme. I will see if that's something I can accommodate going forward.

**Comment by hupfdule** [comment]
The same is true for code blocks with an invalid language specified.

For example the following code block breaks the dark mode (for that page):

    ```invalid
    some test
    ```

If the term `invalid` is removed the dark mode works again.

**Comment by onweru** [comment]
> The same is true for code blocks with an invalid language specified.
> 
> For example the following code block breaks the dark mode (for that page):
> 
> ```
> ```invalid
> some test
> ```
> ```
> 
> If the term `invalid` is removed the dark mode works again.

@hupfdule, I couldn't reproduce the darkmode breaking when I copied this
