### ISSUE TITLE
[Feature] Allow custom CSS

### ISSUE THREAD

**Issue by laundmo** [onweru/compose#38]
**I have checked all the prerequisites below and I'm yet experiencing a problem**

- [x] Read the README.md
- [x] Have the extended version of Hugo installed
- [x] Used the exampleSite's config.toml as a reference

**Describe the bug**

Currently, this theme does not support customCSS like clarity. This is a request to add that feature to this theme too.
[reference implementation in clarity](https://github.com/chipzoller/hugo-clarity/blob/273ce333985b3da67d836a4bc7af6f9633f3ad66/layouts/_default/baseof.html#L40-L44)

**Comment by onweru** [comment]
@laundmo, fixed and [documented here](https://docs.neuralvibes.com/docs/compose/customize/#how-do-i-add-custom-styles-scripts-meta-tags-etc)

**Comment by laundmo** [comment]
@onweru  nice, thanks!
