### ISSUE TITLE
The index of a page should automatically get a button link to the first subpage

### ISSUE THREAD

**Issue by hupfdule** [onweru/compose#45]
**I have checked all the prerequisites below and I'm yet experiencing a problem**

- [x] Read the README.md
- [x] Have the extended version of Hugo installed
- [x] Used the exampleSite's config.toml as a reference

**Describe the bug**

Compose already creates buttons by default to the next and previous page:

![link1](https://user-images.githubusercontent.com/36069345/111919803-178b6d00-8a8c-11eb-9abe-76e83c19e27d.png)

It would be nice if such a button would be created from the index of a page to the first of its subpages automatically. 

Your example site does this manually:

![link2](https://user-images.githubusercontent.com/36069345/111919795-0c384180-8a8c-11eb-9aaa-d15f8d5c3a40.png)

This has the following drawbacks:

1. It must be done manually while it could be done automatically
2. It looks different as the arrow is missing
3. It positioned at the left while the default navigation buttons to go "forward" are positioned at the right.

**Comment by onweru** [comment]
@hupfdule,

> It must be done manually while it could be done automatically

Please submit a PR, I will consider it.

**Comment by hupfdule** [comment]
No. :-)

This is a request for enhancement (feature wish).
I am not able to do this. Therefore I will not even try.

**Comment by onweru** [comment]
In retrospect, users should decide what the button text and where it leads to should be.
