### ISSUE TITLE
Spelling mistake on 404

### ISSUE THREAD

**Issue by Skelmis** [onweru/compose#48]
**Describe the bug**

When experiencing a 404, the site will send the relevant page however it contains the following 
- `Yback home`
I think it should just be
- `back home`

If this *is* the intended spelling / use-case please advise or close this :)

Source for issue can be found [here](https://github.com/onweru/compose/blob/ba7520dfcd8bd5a2aeb2012739428ecdd74018ec/layouts/404.html#L4)

**Comment by onweru** [comment]
Thank you @Skelmis
