### ISSUE TITLE
Favicons are assumed to be in root

### ISSUE THREAD

**Issue by PetrosPapapa** [onweru/compose#49]
**I have checked all the prerequisites below and I'm yet experiencing a problem**

- [x] Read the README.md
- [x] Have the extended version of Hugo installed
- [x] Used the exampleSite's config.toml as a reference

**Describe the bug**

If you set a `baseURL` in a subdirectory of a website/domain (e.g. http://www.example.com/somedirectory), favicons are not loaded properly. This is due to the leading `/` in this line of code:

https://github.com/onweru/compose/blob/dec3f94f9dea42b28921b13ca12d3827c90cbf77/layouts/partials/head.html#L4

It should instead be: `{{- $iconsPath := "favicons/" }}` 

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser: Firefox, Chrome

**Comment by onweru** [comment]
@PetrosPapapa, thank you.
