### ISSUE TITLE
[UX] "Left sidebar" not scrollable before the content hit bottom

### ISSUE THREAD

**Issue by nodablock** [onweru/compose#5]
Hi!

I'm facing an issue when I have a lot of elements in the left sidebar. 
When scrolling down, the "right part", where there is the content is, needs to be totally at the bottom before the left menu is scrollable .

Here how it looks like: 
![Screen Recording 2020-05-08 at 05 05 PM](https://user-images.githubusercontent.com/42296773/81390503-273ce400-914e-11ea-8859-a16198205ef4.gif)

I believe a better experience would be if we can scroll down on the menu independently of the content on the right?

I've tried to dig in, I believe it happen in the `customizeSidebar` function: https://github.com/onweru/compose/blob/fc71674782e3b2415381ea942ca8311b7d109a7c/assets/js/index.js#L150-L199 

Any tips on fixing that?

**Comment by onweru** [comment]
@nodablock,

Thanks for contributing. I will have a look later on and come up with possible remedies.

**Comment by onweru** [comment]
@nodablock,

I have a request, would you mind me taking a look at your code. You know, to have a closer look (play around with it) ... while I go about fixing this.

Thanks.

**Comment by nodablock** [comment]
@onweru sure! my page where the bug happen looks like that: 

```
---
title: "My super tile"
weight: 1
---

# Lorem Ipsum

Est facies potestas, cum tumulo leni mollierant oculos moram antiquis munusque
figuras. Intereat nec Nebrophonosque commune iacentem *puellae ferrumque orbae*
frustra seditio laude, et a et in sentit Credulitas insurgens. Et mersae; Phoebe
fluctibus conlectae **leves** vitamque e levati, posse. Sollicitive multamque
Italis nataeque auras; in vocalis corporibus iram sperato Cephalus sua:
Amphitryoniadae ultima turba! Populabile digitos abstrahor deprensa incunabula
inque, qui movit lentosque.

## Stolidi quasque
Lorem markdownum gravis quodque *quoque dato*, per temptare altera. Mecum
abscidit, mea capillis ab erat sua defensore finita vicibus, sed levor,
pulmonibus finitimi pater erat.

- Nec venis natamque
- Est nec pro amans Parnasos ferox
- Cupiam collabitur adyto
- Harenas sive cum quae
- Orbum fumo moram fixit Ditem

Fremebundus ortus nefandis quoque, sed sponsi bella nunc Dianae domos casu.
Adultera contentus Troiam Iuppiter ei Famem, cantatas nisi. Non tamen, populo
ibat carbasa non Iovi gravidamque Derceti properent! Illa ducit: duxere ergo qui
imago fuit imas sinit bove? Et an nostra exercet fulmine murmure, illa, denegat;
suo.

# Tenuere fixo mihi

Lorem markdownum *eodem*: laetaris nuper et [piasque](http://www.sinitis.io/)
vulnera ereptus inmenso at aures ista tot! Nunc fluctibus si haud paulumque
lactentem *turba* nitidissima virgo praestem in iacuit hospitio frustra quae
avus: ad amisit. Natantia *tibiaque*, gratia, auspiciis peperit, reddebant huic.

> Optare cornua, spemque capit. Quamquam legerat Aeacus reccidimus tristia
> inerant, lentas pronus calores, cum. Ardea et maculosae procul excepit
> ostendens corpore admonitorque coegit.


## Lacrimae quo mutare mea tibi spoliat properare

Densa suos servare orbi vigil sceleris nisi, ira inde vocem heros. Flumina et et
oculos corona felicior invocat in cultos quam, donec. Trepidos umbram at
numerare, arma Bacche, est natum tetendi quod, volucrum, aquas convulso tofis,
coeunt. Eripere antiquas doloris aeraque puero neque omni moveri timeo
contendere fuit Trinacriam.

## Title ABC

Ausoniis sed duos quodque his nomina flecti et tauri concurrit [poterat
renarrant nervis](http://futuros-et.com/). Omnia hominem odoribus spinea paratu
o indicio dolore. Lucidus quae ore, gravis appellantque patria rursus loci motus
puerilibus.

## Title 9999
Densa suos servare orbi vigil sceleris nisi, ira inde vocem heros. Flumina et et
oculos corona felicior invocat in cultos quam, donec. Trepidos umbram at
numerare, arma Bacche, est natum tetendi quod, volucrum, aquas convulso tofis,
coeunt. Eripere antiquas doloris aeraque puero neque omni moveri timeo
contendere fuit Trinacriam.

## Bifurcum titulum vincar tenentibus aderant

Densa suos servare orbi vigil sceleris nisi, ira inde vocem heros. Flumina et et
oculos corona felicior invocat in cultos quam, donec. Trepidos umbram at
numerare, arma Bacche, est natum tetendi quod, volucrum, aquas convulso tofis,
coeunt. Eripere antiquas doloris aeraque puero neque omni moveri timeo
contendere fuit Trinacriam.

## How long does the application take?
Densa suos servare orbi vigil sceleris nisi, ira inde vocem heros. Flumina et et
oculos corona felicior invocat in cultos quam, donec. Trepidos umbram at
numerare, arma Bacche, est natum tetendi quod, volucrum, aquas convulso tofis,
contendere fuit Trinacriam.

## Bifurcum titulum vincar tenentibus aderant

Ausoniis sed duos quodque his nomina flecti et tauri concurrit [poterat
renarrant nervis](http://futuros-et.com/). Omnia hominem odoribus spinea paratu
o indicio dolore. Lucidus quae ore, gravis appellantque patria rursus loci motus
puerilibus.

## Lacrimae quo mutare mea tibi spoliat properare

Densa suos servare orbi vigil sceleris nisi, ira inde vocem heros. Flumina et et
oculos corona felicior invocat in cultos quam, donec. Trepidos umbram at
numerare, arma Bacche, est natum tetendi quod, volucrum, aquas convulso tofis,
coeunt. Eripere antiquas doloris aeraque puero neque omni moveri timeo
contendere fuit Trinacriam.

## Title 9999

Densa suos servare orbi vigil sceleris nisi, ira inde vocem heros. Flumina et et
oculos corona felicior invocat in cultos quam, donec. Trepidos umbram at
numerare, arma Bacche, est natum tetendi quod, volucrum, aquas convulso tofis,
coeunt. Eripere antiquas doloris aeraque puero neque omni moveri timeo
contendere fuit Trinacriam.

## Title ABC
Densa suos servare orbi vigil sceleris nisi, ira inde vocem heros. Flumina et et
oculos corona felicior invocat in cultos quam, donec. Trepidos umbram at
numerare, arma Bacche, est natum tetendi quod, volucrum, aquas convulso tofis,
contendere fuit Trinacriam.

## Cythereius turpe pacifer

Minus ad haec dum, sub repertum loquor Nec neque ipse **iuvencos**. Stamina
exitus *tamen*, eadem ego? Et admissum tempus festas, vertor, diu vidi ipse
sorsque oscula vultusque.

*Nec* piis ego, Veneris in adunca; et adsilientis furorem. Dieque parte
conplexus Ismenus condi, et gestamina fortis in.



## How long does the application take?
Densa suos servare orbi vigil sceleris nisi, ira inde vocem heros. Flumina et et
oculos corona felicior invocat in cultos quam, donec. Trepidos umbram at
numerare, arma Bacche, est natum tetendi quod, volucrum, aquas convulso tofis,
contendere fuit Trinacriam.

## Cythereius turpe pacifer

Minus ad haec dum, sub repertum loquor Nec neque ipse **iuvencos**. Stamina
exitus *tamen*, eadem ego? Et admissum tempus festas, vertor, diu vidi ipse
sorsque oscula vultusque.

*Nec* piis ego, Veneris in adunca; et adsilientis furorem. Dieque parte
conplexus Ismenus condi, et gestamina fortis in.


## How long does the application take?
Densa suos servare orbi vigil sceleris nisi, ira inde vocem heros. Flumina et et
oculos corona felicior invocat in cultos quam, donec. Trepidos umbram at
numerare, arma Bacche, est natum tetendi quod, volucrum, aquas convulso tofis,
contendere fuit Trinacriam.

## Target Target 

Minus ad haec dum, sub repertum loquor Nec neque ipse **iuvencos**. Stamina
exitus *tamen*, eadem ego? Et admissum tempus festas, vertor, diu vidi ipse
sorsque oscula vultusque.

*Nec* piis ego, Veneris in adunca; et adsilientis furorem. Dieque parte
conplexus Ismenus condi, et gestamina fortis in.

## Subiectaque proles mecum tauri

Lorem markdownum, suam callidus. Nec omnis: mihi que animis perque querellas
ignis iusta et inquit potes adveniens quid pondere.

Laticem Cadmeides, numinis adsum, Calydonius et eunti in defensae pressa!
Ignotis et eadem. Longoque undaque Nesso, [his](http://cum-quaeque.org/) deus,
Theseus leones exhalantes vultus comae fulvis aequora fidem orbem sit augerem
spumaque fraude.

Puer esse lacrimarum maius loca quotiens: cum ora, arva, lacrimis cur. Quantas
de fuerat aurum: apte Hippomenes congressus Onetor, se nunc cessasse aureus, et
Eryx et robore concilio. Tamen ego caudam cohibentur risere.

## Bobus inspiratque nostro

Vultus Phaethonteos precor, me letum evolvere ignota membrisque passae quod
expers? Lati sibi refert, concita fibras. Cadmeida impetus omine, in **times**
serpentis *pectora insequor*, et ait nitidum delusa. Centum Agenorides mihi
securosque vix fuit retroque repercusso retentas.

- Actaeas prohibere multo laedere sistetur primis plenaque
- In dixit solus reginam Tantalus carpit inplebat
- Virgo pectore
- Nil vocat somnia defensamus facta volant in

## Target Target 

Lorem markdownum, suam callidus. Nec omnis: mihi que animis perque querellas
ignis iusta et inquit potes adveniens quid pondere.

Laticem Cadmeides, numinis adsum, Calydonius et eunti in defensae pressa!
Ignotis et eadem. Longoque undaque Nesso, [his](http://cum-quaeque.org/) deus,
Theseus leones exhalantes vultus comae fulvis aequora fidem orbem sit augerem
spumaque fraude.

Puer esse lacrimarum maius loca quotiens: cum ora, arva, lacrimis cur. Quantas
de fuerat aurum: apte Hippomenes congressus Onetor, se nunc cessasse aureus, et
Eryx et robore concilio. Tamen ego caudam cohibentur risere.

## Bobus inspiratque nostro

Vultus Phaethonteos precor, me letum evolvere ignota membrisque passae quod
expers? Lati sibi refert, concita fibras. Cadmeida impetus omine, in **times**
serpentis *pectora insequor*, et ait nitidum delusa. Centum Agenorides mihi
securosque vix fuit retroque repercusso retentas.

- Actaeas prohibere multo laedere sistetur primis plenaque
- In dixit solus reginam Tantalus carpit inplebat
- Virgo pectore
- Nil vocat somnia defensamus facta volant in

# Tenuere fixo mihi

Lorem markdownum *eodem*: laetaris nuper et [piasque](http://www.sinitis.io/)
vulnera ereptus inmenso at aures ista tot! Nunc fluctibus si haud paulumque
lactentem *turba* nitidissima virgo praestem in iacuit hospitio frustra quae
avus: ad amisit. Natantia *tibiaque*, gratia, auspiciis peperit, reddebant huic.

> Optare cornua, spemque capit. Quamquam legerat Aeacus reccidimus tristia
> inerant, lentas pronus calores, cum. Ardea et maculosae procul excepit
> ostendens corpore admonitorque coegit.


## Lacrimae quo mutare mea tibi spoliat properare

Densa suos servare orbi vigil sceleris nisi, ira inde vocem heros. Flumina et et
oculos corona felicior invocat in cultos quam, donec. Trepidos umbram at
numerare, arma Bacche, est natum tetendi quod, volucrum, aquas convulso tofis,
coeunt. Eripere antiquas doloris aeraque puero neque omni moveri timeo
contendere fuit Trinacriam.

## Title ABC

Ausoniis sed duos quodque his nomina flecti et tauri concurrit [poterat
renarrant nervis](http://futuros-et.com/). Omnia hominem odoribus spinea paratu
o indicio dolore. Lucidus quae ore, gravis appellantque patria rursus loci motus
puerilibus.

```

**Comment by onweru** [comment]
> @onweru sure! my page where the bug happen looks like that:
> 
> ```
> ---
> title: "My super tile"
> weight: 1
> ---
> 
> # Lorem Ipsum
> 
> Est facies potestas, cum tumulo leni mollierant oculos moram antiquis munusque
> figuras. Intereat nec Nebrophonosque commune iacentem *puellae ferrumque orbae*
> frustra seditio laude, et a et in sentit Credulitas insurgens. Et mersae; Phoebe
> fluctibus conlectae **leves** vitamque e levati, posse. Sollicitive multamque
> Italis nataeque auras; in vocalis corporibus iram sperato Cephalus sua:
> Amphitryoniadae ultima turba! Populabile digitos abstrahor deprensa incunabula
> inque, qui movit lentosque.
> 
> ## Stolidi quasque
> Lorem markdownum gravis quodque *quoque dato*, per temptare altera. Mecum
> abscidit, mea capillis ab erat sua defensore finita vicibus, sed levor,
> pulmonibus finitimi pater erat.
> 
> - Nec venis natamque
> - Est nec pro amans Parnasos ferox
> - Cupiam collabitur adyto
> - Harenas sive cum quae
> - Orbum fumo moram fixit Ditem
> 
> Fremebundus ortus nefandis quoque, sed sponsi bella nunc Dianae domos casu.
> Adultera contentus Troiam Iuppiter ei Famem, cantatas nisi. Non tamen, populo
> ibat carbasa non Iovi gravidamque Derceti properent! Illa ducit: duxere ergo qui
> imago fuit imas sinit bove? Et an nostra exercet fulmine murmure, illa, denegat;
> suo.
> 
> # Tenuere fixo mihi
> 
> Lorem markdownum *eodem*: laetaris nuper et [piasque](http://www.sinitis.io/)
> vulnera ereptus inmenso at aures ista tot! Nunc fluctibus si haud paulumque
> lactentem *turba* nitidissima virgo praestem in iacuit hospitio frustra quae
> avus: ad amisit. Natantia *tibiaque*, gratia, auspiciis peperit, reddebant huic.
> 
> > Optare cornua, spemque capit. Quamquam legerat Aeacus reccidimus tristia
> > inerant, lentas pronus calores, cum. Ardea et maculosae procul excepit
> > ostendens corpore admonitorque coegit.
> 
> 
> ## Lacrimae quo mutare mea tibi spoliat properare
> 
> Densa suos servare orbi vigil sceleris nisi, ira inde vocem heros. Flumina et et
> oculos corona felicior invocat in cultos quam, donec. Trepidos umbram at
> numerare, arma Bacche, est natum tetendi quod, volucrum, aquas convulso tofis,
> coeunt. Eripere antiquas doloris aeraque puero neque omni moveri timeo
> contendere fuit Trinacriam.
> 
> ## Title ABC
> 
> Ausoniis sed duos quodque his nomina flecti et tauri concurrit [poterat
> renarrant nervis](http://futuros-et.com/). Omnia hominem odoribus spinea paratu
> o indicio dolore. Lucidus quae ore, gravis appellantque patria rursus loci motus
> puerilibus.
> 
> ## Title 9999
> Densa suos servare orbi vigil sceleris nisi, ira inde vocem heros. Flumina et et
> oculos corona felicior invocat in cultos quam, donec. Trepidos umbram at
> numerare, arma Bacche, est natum tetendi quod, volucrum, aquas convulso tofis,
> coeunt. Eripere antiquas doloris aeraque puero neque omni moveri timeo
> contendere fuit Trinacriam.
> 
> ## Bifurcum titulum vincar tenentibus aderant
> 
> Densa suos servare orbi vigil sceleris nisi, ira inde vocem heros. Flumina et et
> oculos corona felicior invocat in cultos quam, donec. Trepidos umbram at
> numerare, arma Bacche, est natum tetendi quod, volucrum, aquas convulso tofis,
> coeunt. Eripere antiquas doloris aeraque puero neque omni moveri timeo
> contendere fuit Trinacriam.
> 
> ## How long does the application take?
> Densa suos servare orbi vigil sceleris nisi, ira inde vocem heros. Flumina et et
> oculos corona felicior invocat in cultos quam, donec. Trepidos umbram at
> numerare, arma Bacche, est natum tetendi quod, volucrum, aquas convulso tofis,
> contendere fuit Trinacriam.
> 
> ## Bifurcum titulum vincar tenentibus aderant
> 
> Ausoniis sed duos quodque his nomina flecti et tauri concurrit [poterat
> renarrant nervis](http://futuros-et.com/). Omnia hominem odoribus spinea paratu
> o indicio dolore. Lucidus quae ore, gravis appellantque patria rursus loci motus
> puerilibus.
> 
> ## Lacrimae quo mutare mea tibi spoliat properare
> 
> Densa suos servare orbi vigil sceleris nisi, ira inde vocem heros. Flumina et et
> oculos corona felicior invocat in cultos quam, donec. Trepidos umbram at
> numerare, arma Bacche, est natum tetendi quod, volucrum, aquas convulso tofis,
> coeunt. Eripere antiquas doloris aeraque puero neque omni moveri timeo
> contendere fuit Trinacriam.
> 
> ## Title 9999
> 
> Densa suos servare orbi vigil sceleris nisi, ira inde vocem heros. Flumina et et
> oculos corona felicior invocat in cultos quam, donec. Trepidos umbram at
> numerare, arma Bacche, est natum tetendi quod, volucrum, aquas convulso tofis,
> coeunt. Eripere antiquas doloris aeraque puero neque omni moveri timeo
> contendere fuit Trinacriam.
> 
> ## Title ABC
> Densa suos servare orbi vigil sceleris nisi, ira inde vocem heros. Flumina et et
> oculos corona felicior invocat in cultos quam, donec. Trepidos umbram at
> numerare, arma Bacche, est natum tetendi quod, volucrum, aquas convulso tofis,
> contendere fuit Trinacriam.
> 
> ## Cythereius turpe pacifer
> 
> Minus ad haec dum, sub repertum loquor Nec neque ipse **iuvencos**. Stamina
> exitus *tamen*, eadem ego? Et admissum tempus festas, vertor, diu vidi ipse
> sorsque oscula vultusque.
> 
> *Nec* piis ego, Veneris in adunca; et adsilientis furorem. Dieque parte
> conplexus Ismenus condi, et gestamina fortis in.
> 
> 
> 
> ## How long does the application take?
> Densa suos servare orbi vigil sceleris nisi, ira inde vocem heros. Flumina et et
> oculos corona felicior invocat in cultos quam, donec. Trepidos umbram at
> numerare, arma Bacche, est natum tetendi quod, volucrum, aquas convulso tofis,
> contendere fuit Trinacriam.
> 
> ## Cythereius turpe pacifer
> 
> Minus ad haec dum, sub repertum loquor Nec neque ipse **iuvencos**. Stamina
> exitus *tamen*, eadem ego? Et admissum tempus festas, vertor, diu vidi ipse
> sorsque oscula vultusque.
> 
> *Nec* piis ego, Veneris in adunca; et adsilientis furorem. Dieque parte
> conplexus Ismenus condi, et gestamina fortis in.
> 
> 
> ## How long does the application take?
> Densa suos servare orbi vigil sceleris nisi, ira inde vocem heros. Flumina et et
> oculos corona felicior invocat in cultos quam, donec. Trepidos umbram at
> numerare, arma Bacche, est natum tetendi quod, volucrum, aquas convulso tofis,
> contendere fuit Trinacriam.
> 
> ## Target Target 
> 
> Minus ad haec dum, sub repertum loquor Nec neque ipse **iuvencos**. Stamina
> exitus *tamen*, eadem ego? Et admissum tempus festas, vertor, diu vidi ipse
> sorsque oscula vultusque.
> 
> *Nec* piis ego, Veneris in adunca; et adsilientis furorem. Dieque parte
> conplexus Ismenus condi, et gestamina fortis in.
> 
> ## Subiectaque proles mecum tauri
> 
> Lorem markdownum, suam callidus. Nec omnis: mihi que animis perque querellas
> ignis iusta et inquit potes adveniens quid pondere.
> 
> Laticem Cadmeides, numinis adsum, Calydonius et eunti in defensae pressa!
> Ignotis et eadem. Longoque undaque Nesso, [his](http://cum-quaeque.org/) deus,
> Theseus leones exhalantes vultus comae fulvis aequora fidem orbem sit augerem
> spumaque fraude.
> 
> Puer esse lacrimarum maius loca quotiens: cum ora, arva, lacrimis cur. Quantas
> de fuerat aurum: apte Hippomenes congressus Onetor, se nunc cessasse aureus, et
> Eryx et robore concilio. Tamen ego caudam cohibentur risere.
> 
> ## Bobus inspiratque nostro
> 
> Vultus Phaethonteos precor, me letum evolvere ignota membrisque passae quod
> expers? Lati sibi refert, concita fibras. Cadmeida impetus omine, in **times**
> serpentis *pectora insequor*, et ait nitidum delusa. Centum Agenorides mihi
> securosque vix fuit retroque repercusso retentas.
> 
> - Actaeas prohibere multo laedere sistetur primis plenaque
> - In dixit solus reginam Tantalus carpit inplebat
> - Virgo pectore
> - Nil vocat somnia defensamus facta volant in
> 
> ## Target Target 
> 
> Lorem markdownum, suam callidus. Nec omnis: mihi que animis perque querellas
> ignis iusta et inquit potes adveniens quid pondere.
> 
> Laticem Cadmeides, numinis adsum, Calydonius et eunti in defensae pressa!
> Ignotis et eadem. Longoque undaque Nesso, [his](http://cum-quaeque.org/) deus,
> Theseus leones exhalantes vultus comae fulvis aequora fidem orbem sit augerem
> spumaque fraude.
> 
> Puer esse lacrimarum maius loca quotiens: cum ora, arva, lacrimis cur. Quantas
> de fuerat aurum: apte Hippomenes congressus Onetor, se nunc cessasse aureus, et
> Eryx et robore concilio. Tamen ego caudam cohibentur risere.
> 
> ## Bobus inspiratque nostro
> 
> Vultus Phaethonteos precor, me letum evolvere ignota membrisque passae quod
> expers? Lati sibi refert, concita fibras. Cadmeida impetus omine, in **times**
> serpentis *pectora insequor*, et ait nitidum delusa. Centum Agenorides mihi
> securosque vix fuit retroque repercusso retentas.
> 
> - Actaeas prohibere multo laedere sistetur primis plenaque
> - In dixit solus reginam Tantalus carpit inplebat
> - Virgo pectore
> - Nil vocat somnia defensamus facta volant in
> 
> # Tenuere fixo mihi
> 
> Lorem markdownum *eodem*: laetaris nuper et [piasque](http://www.sinitis.io/)
> vulnera ereptus inmenso at aures ista tot! Nunc fluctibus si haud paulumque
> lactentem *turba* nitidissima virgo praestem in iacuit hospitio frustra quae
> avus: ad amisit. Natantia *tibiaque*, gratia, auspiciis peperit, reddebant huic.
> 
> > Optare cornua, spemque capit. Quamquam legerat Aeacus reccidimus tristia
> > inerant, lentas pronus calores, cum. Ardea et maculosae procul excepit
> > ostendens corpore admonitorque coegit.
> 
> 
> ## Lacrimae quo mutare mea tibi spoliat properare
> 
> Densa suos servare orbi vigil sceleris nisi, ira inde vocem heros. Flumina et et
> oculos corona felicior invocat in cultos quam, donec. Trepidos umbram at
> numerare, arma Bacche, est natum tetendi quod, volucrum, aquas convulso tofis,
> coeunt. Eripere antiquas doloris aeraque puero neque omni moveri timeo
> contendere fuit Trinacriam.
> 
> ## Title ABC
> 
> Ausoniis sed duos quodque his nomina flecti et tauri concurrit [poterat
> renarrant nervis](http://futuros-et.com/). Omnia hominem odoribus spinea paratu
> o indicio dolore. Lucidus quae ore, gravis appellantque patria rursus loci motus
> puerilibus.
> ```

Thank you
