### ISSUE TITLE
User guide is broken link

### ISSUE THREAD

**Issue by chipzoller** [onweru/compose#56]
In https://github.com/onweru/compose#examplesite the user guide link is broken. Hope you're well :)

**Comment by onweru** [comment]
Thanks @chipzoller. Fixing it right away. I'm doing well my friend, hope you're too.

**Comment by chipzoller** [comment]
Fixed by Weru!

**Comment by chipzoller** [comment]
Another broken link to "shortcodes" in https://docs.neuralvibes.com/docs/compose/organize-content/
