### ISSUE TITLE
[Bug] Fenced code blocks without language render differently

### ISSUE THREAD

**Issue by chipzoller** [onweru/compose#57]
**I have checked all the prerequisites below and I'm yet experiencing a problem**

- [x] Read the README.md
- [x] Have the extended version of Hugo installed
- [x] Used the exampleSite's config.toml as a reference

**Describe the bug**

When fenced code blocks are used without a language, they display (and cause the tool palette buttons to be displayed) differently which causes some collisions.

<img width="852" alt="image" src="https://user-images.githubusercontent.com/29008123/143325236-e9414c07-98ad-411b-a45f-f75d2d5119cd.png">

vs

<img width="866" alt="image" src="https://user-images.githubusercontent.com/29008123/143325294-57e5c0a6-e52e-4df5-8b29-1691415adbf6.png">

**Desktop (please complete the following information):**
 - OS: Mac 10.14.6
 - Browser: Firefox 93.0

**Comment by chipzoller** [comment]
Don't see a visual change based on the fix.

**Comment by onweru** [comment]
I will check again.

**Comment by chipzoller** [comment]
Confirmed fixed. I didn't update the Hugo module.
