### ISSUE TITLE
[Feature] Favicon path move to /static/images

### ISSUE THREAD

**Issue by chipzoller** [onweru/compose#65]
**I have checked all the prerequisites below and I'm yet experiencing a problem**

- [x] Read the README.md
- [x] Have the extended version of Hugo installed
- [x] Used the exampleSite's config.toml as a reference

**Describe the bug**

All branding assets for this theme related to images need to be stored together without having some components coming from the theme while others come from site directories. The thing missing here is favicons, which still are configured to point to the theme directory. Change these so that they can be picked up from `/static/images` just like the banner images.

**Desktop (please complete the following information):**
 - OS: N/A
 - Browser: N/A

**Comment by onweru** [comment]
> The thing missing here is favicons, which still are configured to point to the theme directory.

@chipzoller, this is the desired behaviour. You can override favicons from the site directory. This way, the theme isn't dependent on the theme to function.

**Comment by chipzoller** [comment]
Can you provide some instruction on this in your docs, or is this a generic Hugo topic? Even if so, it may be kind of you to point users there.
