### ISSUE TITLE
[UX] On mobile, hide the header when scrolling down

### ISSUE THREAD

**Issue by nodablock** [onweru/compose#7]
This is mostly a feature request. 

I believe the "top menu bar" does not need to be visible when you start scrolling the content it is taking a good amount of space, especially on small devices.

**Comment by onweru** [comment]
> This is mostly a feature request.
> 
> I believe the "top menu bar" does not need to be visible when you start scrolling the content it is taking a good amount of space, especially on small devices.

@nodablock 
For this to work, we would need a back to top icon or a sticky hamburger. What do you think?

**Comment by nodablock** [comment]
@onweru an easy solution would be to make it appear when we scroll up.
I've posted how I did it in  https://github.com/onweru/compose/issues/6#issuecomment-635093176
