### ISSUE TITLE
[BUG] No "visible" shadow effect in dark mode at "Search the docs"

### ISSUE THREAD

**Issue by jaiakash** [onweru/compose#70]
There is a shadow effect around the "search the docs" when the website is used in light mode. But when used in a dark mode, there is no "visible" shadow effect.

![Screenshot from 2022-01-28 18-56-08](https://user-images.githubusercontent.com/33419526/151555266-a5dc0ccd-11b6-4a66-8258-4dd73826b17d.png) ![Screenshot from 2022-01-28 18-56-15](https://user-images.githubusercontent.com/33419526/151555277-35c50630-7f3c-4f0d-b8e8-81c1ebb6845c.png)

**Comment by onweru** [comment]
@jaiakash, that was something I deliberately left out. In dark mode, using shadows can easily look weird. I do agree though that we need some sort of feedback. If it has to be a shadow, then it has to be well thought out. I will explore
