### ISSUE TITLE
Error building site[BUG]

### ISSUE THREAD

**Issue by codthing** [onweru/compose#85]
**I have checked all the prerequisites below and I'm yet experiencing a problem**

- [x] Read the README.md
- [x] Have the extended version of Hugo installed
- [x] Used the exampleSite's config.toml as a reference

**Describe the bug**
![image](https://user-images.githubusercontent.com/16655229/165832062-3777389f-1bb3-4cb6-a1ed-d2df8dced99c.png)

A clear and concise description of what the bug is. [REPLACE]

**Desktop (please complete the following information):**
 - OS: [Windows 10]
 - Browser: [102.0.5005.22]

**Comment by onweru** [comment]
Thanks @codthing, I will look into it.

**Comment by onweru** [comment]
@codthing, did you find help?
