### ISSUE TITLE
Images are not rendering

### ISSUE THREAD

**Issue by nixon0630** [onweru/compose#87]
I'm trying to upload "public" folder into my host's "public_html" folder (cpanel). Website works fine, but images are not displaying. 

I tried to change "const rootURL = window.location.protocol + "//" + window.location.host;" as [here](https://github.com/onweru/compose/pull/75/commits/c924c0bb413c10408b160bad624b4a30e21166d9) to "const rootURL = '{{ strings.TrimSuffix "/" .Site.BaseURL }}/';". However, after that my website stoppped rendering even buttons. How can I fix it?

**Comment by nixon0630** [comment]
It now got even worse. When I'm trying to run server locally, it says:
Error: add site dependencies: load resources: loading translations: "/home/nixon0630/Desktop/olympiadmath/themes/compose/i18n/en.toml:1:1": failed to load translations: toml: invalid character at start of key: 

@onweru, can you please help to fix it?

**Comment by onweru** [comment]
@nixon0630, what is the url of your website?

**Comment by nixon0630** [comment]
Here is it:
http://olympiadmath.uz/
Now it cannot display the theme itself, but in local server it looks pretty good:

![Screenshot from 2022-12-30 16-25-09](https://user-images.githubusercontent.com/63713856/210065352-07db88e9-5363-44df-b8ee-e3788d750f3a.png)

**Comment by onweru** [comment]
@nixon0630,

I suspect this has to do with your `baseURL` value in the config. Looking at your website, the baseURL is set to `http://olympiadmath.uz/olympiadmath.uz/`

Are you sure, than in your site is hosted inside a subdir `olympiadmath.uz` ?

**Comment by nixon0630** [comment]
How can I change it to the olympiadmath.uz?

**Comment by onweru** [comment]
> @nixon0630,
> 
> I suspect this has to do with your `baseURL` value in the config. Looking at your website, the baseURL is set to `http://olympiadmath.uz/olympiadmath.uz/`
> 
> Are you sure, than in your site is hosted inside a subdir `olympiadmath.uz` ?

Oh shoot! I think you're just using `olympiadmath.uz` as the baseURL. It should be `https://olympiadmath.uz/`

<img width="335" alt="SCR-20221230-k6g" src="https://user-images.githubusercontent.com/16350351/210065945-59fb78a7-e7f5-4b0b-97c1-5c18b86db6fd.png">

**Comment by onweru** [comment]
Like so:

<img width="455" alt="SCR-20221230-k8l" src="https://user-images.githubusercontent.com/16350351/210066060-3f8bfcf8-3c10-4c26-981d-9113bcc095f0.png">

Otherwise `olympiadmath.uz` will be treated as a relative link to a subfolder.

**Comment by nixon0630** [comment]
Sure, it shows images now
But it doesn't display theme

**Comment by nixon0630** [comment]
Pleashe help

like it reversed now (earlier cannot load images, but there; now an load images but not theme)

**Comment by nixon0630** [comment]
Unofrtuntely, some images [here](https://olympiadmath.uz/geometry/inversion/) are still invisible, but theme works fine.

**Comment by onweru** [comment]
The https version works fine. Make sure you set a 301 redirect for all `http` to `https`

<img width="1368" alt="SCR-20221230-kbg" src="https://user-images.githubusercontent.com/16350351/210066352-6a956e06-1d14-4b79-8dd5-1e0fea3acc76.png">

**Comment by nixon0630** [comment]
Maybe I should replicate diy image (.svg) with another format?

**Comment by onweru** [comment]
> Maybe I should replicate diy image (.svg) with another format?

Not necessarily. Just ensure you have the image as named inside static/images directory.
<img width="320" alt="SCR-20221230-ke9" src="https://user-images.githubusercontent.com/16350351/210066645-c9c3772f-201a-4716-8bb7-c5ce8677be21.png">

I will mark this issue as resolved now. If you have other issues, please open a [discussion](https://github.com/onweru/compose/discussions).

**Comment by nixon0630** [comment]
@onweru, some images are not displaying still, but some do. For example, [here](https://olympiadmath.uz/geometry/inversion/) [this](https://olympiadmath.uz/images/inversion_1.png) image is visible, but somehow [this](https://olympiadmath.uz/images/inversion_2.png) is not. On localhost it works fine still.

**Comment by onweru** [comment]
@nixon0630, this is not a bug. Ensure you are following the following tips to avoid the inconsistencies:

All image filenames

1/   should be in hyphenated (no spaces in the name)
2/  should be in lowercase
3/  inside `static/images` dir
4/ avoid uppercase file-extensions e.g .JPG, .PNG. Use .jpg, .png instead.
