### ISSUE TITLE
[FEATURE] Render goldmark taskList checkboxes

### ISSUE THREAD

**Issue by Ppjet6** [onweru/compose#93]
**I have checked all the prerequisites below and I don't see this is available**

- [x] Read the README.md
- [x] Have the extended version of Hugo installed
- [x] Used the exampleSite's config.toml as a reference

**Describe the feature**

https://github.github.com/gfm/#task-list-items-extension-

The `taskList` extension for goldmark markdown (enabled by default in hugo) produces the following html:
```
<ul>
<li><input disabled="" type="checkbox"> foo</li>
<li><input checked="" disabled="" type="checkbox"> bar</li>
</ul>
```

I can see these in the generated html for my article, but they are not rendered on the website. It seems there are a few things that prevent it from being displayed but I'm not entirely sure what.

First `-webkit-appearance: none` seems to be set. I also had to add `display: initial` on the element to be able to see it.
Then it seems github also sets `list-style-type: none`, which does make it look better.
I'm not sure if they have anything else used to move it slightly to the left and make the space less awkward.

Of course github doesn't need to be copied :)

**Desktop (please complete the following information):**
 - OS: Linux
 - Browser: Firefox nightly 111.0a1

**Comment by onweru** [comment]
@Ppjet6, this should now be resolved. please test
