### ISSUE TITLE
Adding code snippets breaks dark theme

### ISSUE THREAD

**Issue by Ppjet6** [onweru/compose#94]
**I have checked all the prerequisites below and I'm yet experiencing a problem**

- [x] Read the README.md
- [x] Have the extended version of Hugo installed
- [x] Used the exampleSite's config.toml as a reference

**Describe the bug**

When I use blockquotes in markdown, the blockquote is properly displayed on the page but I am forced back in the light theme and it's not possible to change this. It also breaks some other parts of the page, such as parts of the left navbar.

**Desktop (please complete the following information):**
 - OS: Linux
 - Browser: Firefox nightly 111.0a1

**Comment by onweru** [comment]
@Ppjet6, that's by design.

**Comment by onweru** [comment]
If you want to adjust the chroma classes, you're out of luck with this theme.

**Comment by Ppjet6** [comment]
Is it by design that blockquotes break the theme?

**Comment by onweru** [comment]
Umh, is that the same issue or a separate issue?

**Comment by Ppjet6** [comment]
It's the same issue. It's the html that gets generated when I use blockquotes, as mentioned in the first post.

**Comment by onweru** [comment]
It seems I misunderstood and misspoke. That said, I still don't get what `pre@class="chroma"` in the title has to do with a blockquote.

Did a quick test and couldn't quite reproduce what you've described. Can you paste an example here? or send me a link

**Comment by Ppjet6** [comment]
https://codeberg.org/joinjabber/website-hugo/commit/3874c788bd7849d6b9f6ae93710265af9e254720

This is an example of a workaround for this issue. I guess you can clone the website to try and reproduce.

**Comment by onweru** [comment]
By all means. You didn't provide an actual example where the problem was happening. I see no blockquotes on the link, or how the `chroma` class is relevant.

**Comment by poVoq** [comment]
Something on our website currently breaks block-quotes. I have a suspicion that it might be related to adding the `custom.js` as explained here: https://docs.neuralvibes.com/docs/compose/customize/#i-want-to-add-custom-sass-or-js

**Comment by Ppjet6** [comment]
Yeah it seems whatever generates `<pre class="chroma">` breaks our theme currently. That's at least blockquotes and code blocks.

**Comment by onweru** [comment]
Or maybe you have different [markup settings](https://github.com/onweru/compose/blob/9412f10b0de552fe15dc98faf7e56ecd67f45c52/exampleSite/config/_default/markup.toml#L6-L15) . If that's the case, that would explain it.

**Comment by onweru** [comment]
The markup settings should match 👇🏼 as is in the exampleSite.

```
codeFences = true
  guessSyntax = false
  hl_Lines = ""
  lineNoStart = 1
  lineNos = true
  lineNumbersInTable = false
  noClasses = false
  style = "monokai"
  tabWidth = 2
```

**Comment by Ppjet6** [comment]
Ok it looks like this is unrelated to `chroma` anyway. I tried removing the only place in your code that adds it to `<pre>` and it didn't fix it.

We use the default configuration so this isn't it either.

It's probably something in our [custom sass](https://codeberg.org/joinjabber/website-hugo/src/branch/main/assets/sass/_variables.sass) that breaks it as @poVoq said. We need to figure out what.

**Comment by ltGuillaume** [comment]
For me, this _only_ happens when I use a code block, so 3x tilde like

```
this
```

It has _nothing_ to do with custom SASS (I removed it all when testing).

**Comment by ltGuillaume** [comment]
@Ppjet6 has linked to it twice here, but it's https://codeberg.org/joinjabber/website-hugo/

There is no code block added to main branch right now because of the issue, but just add it yourself and you'll see it.

**Comment by onweru** [comment]
@ltGuillaume, thank you that clarification went a long way. It wasn't immediately obvious that was the fork. Plus the talk about blockquotes didn't help with the confusion. This issue was about the code blocks/snippets breaking certain javascript functions.

I have tested with your repo and discovered a javascript bug. Your repo should now work properly 👇🏼, after pulling the update.
 
<img width="1423" alt="SCR-20230209-qwp" src="https://user-images.githubusercontent.com/16350351/217876714-a51b631f-fc59-4bc9-ada6-22d437fd2416.png">

**Comment by Ppjet6** [comment]
Thanks! This indeed fixes it.

To explain why the `baseUrl = "/"` if it isn't obvious, we're serving the website over multiple domains, joinjabber.org, and a Tor onion domain!

Sorry again for the confusion and thanks for taking the time.
